
CREATE TABLE `lend_portfolio_plans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phase` int(11) NOT NULL,
  `phases` int(11) NOT NULL,
  `repayDay` date NOT NULL COMMENT '***???',
  `repayInterest` decimal(16,2) NOT NULL COMMENT '***???',
  `repayPrincipal` decimal(16,2) NOT NULL COMMENT '***???',
  `repayTotal` decimal(16,2) NOT NULL COMMENT '***???',
  `restPrincipal` decimal(16,2) NOT NULL COMMENT '***???',
  `state` varchar(32) NOT NULL COMMENT '***???',
  `version` int(11) DEFAULT NULL COMMENT '***??',
  `normalRepayRequestAdded` tinyint(1) NOT NULL DEFAULT '0',
  `smsNotified` tinyint(1) NOT NULL DEFAULT '0',
  `repaymentRemindInfoAdded` tinyint(1) NOT NULL,
  `lastPhase` bit(1) NOT NULL,
  `repayMgmtFee` decimal(16,2) NOT NULL,
  `repay_guarantee_fee` decimal(16,2) DEFAULT '0.00',
  `repay_guarantee_mgmt_fee` decimal(16,2) DEFAULT '0.00',
  `repayOtherFees` decimal(16,2) NOT NULL,
  `lastUpdateTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `inAdvanceReserveRepaid` bit(1) NOT NULL,
  `debt_id` int(11) NOT NULL DEFAULT '0',
  `orig_principal` decimal(16,2) NOT NULL COMMENT '????',
  `penalty_interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '????????',
  `liquidated_fee` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '?????????',
  `inadvance_bonus` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '?????????????',
  `inadvance_liquidated` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '???????????',
  `calculate_date` date DEFAULT NULL COMMENT '?????',
  `value_start_date` date DEFAULT NULL COMMENT '???',
  `value_end_date` date DEFAULT NULL COMMENT '???',
  `source` varchar(16) NOT NULL DEFAULT 'THREAD' COMMENT '????',
  `relation_id` int(11) NOT NULL COMMENT '????id(??id)',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'åˆ›å»ºæ—¶é—´',
  `mgmt_fee_penalty_interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '服务费违约金',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_lend_portfolio_plan_relationid_phase_source` (`relation_id`,`source`,`phase`),
  KEY `idx_lend_portfolio_plan_state` (`state`),
  KEY `idx_lend_portfolio_plan_phase` (`phase`),
  KEY `idx_lend_portfolio_plan_repay_day` (`repayDay`),
  KEY `idx_lend_portfolio_plan_normal_repay_req_added` (`normalRepayRequestAdded`),
  KEY `idx_lend_portfolio_plan_sms_notified` (`smsNotified`),
  KEY `idx_lend_portfolio_plan_repayment_remind_info_added` (`repaymentRemindInfoAdded`),
  KEY `idx_lend_portfolio_plans_debtid` (`debt_id`),
  KEY `lend_portfolio_plans_lastupdatetime_lpp_idx` (`lastUpdateTime`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34903629 DEFAULT CHARSET=utf8

CREATE TABLE `lend_portfolio_repay_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `deductAmount` decimal(16,2) NOT NULL,
  `liquidatedFee` decimal(16,2) NOT NULL,
  `overDueDays` int(11) NOT NULL COMMENT '***可空',
  `penaltyInterest` decimal(16,2) NOT NULL,
  `repaidAmount` decimal(16,2) NOT NULL,
  `time` date DEFAULT NULL,
  `plan_id` int(11) NOT NULL,
  `overDueNumber` int(11) NOT NULL DEFAULT '0',
  `autoReserveRepaid` tinyint(1) NOT NULL DEFAULT '0',
  `autoPaid` tinyint(1) NOT NULL DEFAULT '0',
  `operateTime` date DEFAULT NULL,
  `inadvance_bonus` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '当期应付提前还款手续费返还',
  `inadvance_liquidated` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '当期应还提前还款违约金',
  `last_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `lender_actual_repay_day` datetime DEFAULT NULL,
  `calculate_overdue_days` int(11) NOT NULL,
  `version` int(11) DEFAULT '0' COMMENT '控制乐观锁',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_50o6mr6yknk6r179jcybpm6a4` (`plan_id`),
  KEY `FKD8F2F39130DDFD52` (`plan_id`),
  KEY `idx_lend_portfolio_repay_record_time` (`time`),
  KEY `idx_lend_portfolio_repay_record_overdue_days` (`overDueDays`),
  KEY `idx_lend_portfolio_repay_record_auto_repaid` (`autoReserveRepaid`),
  KEY `idx_lend_portfolio_repay_record_operate_time` (`operateTime`),
  KEY `idx_idx_lend_portfolio_repay_record_auto_repaid` (`autoReserveRepaid`)
) ENGINE=InnoDB AUTO_INCREMENT=34944494 DEFAULT CHARSET=utf8


CREATE TABLE `record_repay_asset` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `debt_cycle_id` int(11) NOT NULL,
  `correction_debt_cycley_id` int(11) NOT NULL COMMENT '回滚债务周期ID',
  `debt_id` int(11) NOT NULL,
  `relation_id` int(11) NOT NULL,
  `repay_phase` int(11) NOT NULL COMMENT '还款期数',
  `repay_business_type` varchar(16) NOT NULL COMMENT '还款业务类型，友信还款、银行还款',
  `repay_type` varchar(16) NOT NULL COMMENT '还款类型：正常还款、逾期还款、伪逾期还款、提前还款',
  `actual_repay_day` date NOT NULL COMMENT '系统调整后实际还款日期，按照此日期进行罚息计算',
  `lender_actual_repay_day` date NOT NULL COMMENT '指定还款日期，一般由调用指定。',
  `calculate_overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '逾期天数，按照此天数进行计算罚息',
  `overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '实际逾期天数，还款时，距离最近1期已还款的还款日的天数',
  `route_name` varchar(64) NOT NULL COMMENT '分发名称：友信-0期-正常还款、石嘴山-代收-正常还款等',
  `fund_source` varchar(32) NOT NULL,
  `holding_unit` varchar(32) NOT NULL COMMENT '债权持有单位：理财人、公司，还款时，当期债权持有对象',
  `holding_id` varchar(32) NOT NULL COMMENT '还款时，当期债权持有ID,理财人则为理财人id，公司则为签约主体',
  `principal` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '本金',
  `interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '利息',
  `mgmt_fee` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '服务费',
  `penalty_interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '罚息',
  `liquidated` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '违约金',
  `bonus` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '返还',
  `deduct_amount` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '申请减免金额（对应还款记录原deductAmount）',
  `auto_deduct_amount` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '自动减免金额（目前仅用于7天自动减免金额，和deduct_amount之和等于还款记录deductAmount）',
  `red_package_amount` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '优惠红包减免',
  `guarantee_fee` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '保障金',
  `guarantee_mgmt_fee` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '保障金服务费',
  `renrendai_reserve_account` varchar(32) DEFAULT 'UNRESERVED' COMMENT '垫付账户',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  `penalty_fee` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '滞纳金',
  `compens_penalty_interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '理赔罚息',
  `original_compliance_charged_rule` varchar(32) NOT NULL DEFAULT 'DEFAULT' COMMENT '原始计费规则',
  `usage_compliance_charged_rule` varchar(32) NOT NULL DEFAULT 'DEFAULT' COMMENT '当前使用计费规则',
  `cap_repay_all_total` decimal(16,2) DEFAULT '0.00' COMMENT 'CAP结清总额',
  `repay_all_total` decimal(16,2) DEFAULT '0.00' COMMENT '结清总额',
  `cap_can_use_fee` decimal(16,2) DEFAULT '0.00' COMMENT 'CAP结清可收息费',
  `cap_actual_use_fee` decimal(16,2) DEFAULT '0.00' COMMENT 'CAP结清实收息费',
  `cap_deduct_amount` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT 'cap减免',
  `cap_bonus` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT 'cap返还',
  `whole_repay` bit(1) NOT NULL DEFAULT b'1' COMMENT '当期还款期次是否结清',
  `mgmt_fee_penalty_interest` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '服务费违约金',
  `defer_charged_rule` varchar(32) NOT NULL DEFAULT 'NOT' COMMENT '展期规则',
  `defer_repay_all_total` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '展期总额',
  `defer_deduct_amount` decimal(16,2) NOT NULL DEFAULT '0.00' COMMENT '展期减免金额',
  PRIMARY KEY (`id`),
  KEY `indx_record_repay_asset_debt_cycle_id` (`debt_cycle_id`),
  KEY `indx_create_time` (`create_time`),
  KEY `indx_repay_asset_relation_id_phase_correction` (`relation_id`,`repay_phase`,`correction_debt_cycley_id`) USING BTREE,
  KEY `indx_repay_asset_debt_id_phase_correction` (`debt_id`,`repay_phase`,`correction_debt_cycley_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4927804 DEFAULT CHARSET=utf8
CREATE TABLE `debt_exts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `end_date` date DEFAULT NULL COMMENT '终止日期',
  `first_repay_date` date DEFAULT NULL COMMENT '首次还款日',
  `full_bonus` tinyint(1) DEFAULT '0' COMMENT '全额返还标志位',
  `fund_source` varchar(32) DEFAULT NULL COMMENT '资金来源',
  `channel_type` varchar(32) DEFAULT NULL COMMENT '渠道类型',
  `lender_name` varchar(64) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '借款人姓名',
  `lender_mobile` varchar(32) DEFAULT NULL,
  `lender_idno` varchar(18) NOT NULL COMMENT '借款人身份证号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `floating_fee_rate` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否是浮动费率',
  `signed_company` varchar(32) NOT NULL COMMENT '进件推标主体',
  `pre_mgmt_fee_type` varchar(32) DEFAULT 'SIGN_FEE' COMMENT '期初服务费类型',
  `inadvance_repay_liquidated_fee_base` varchar(32) DEFAULT NULL COMMENT '提前还款违约金计算基数',
  `overdue_repay_base_penalty` varchar(32) NOT NULL COMMENT '罚息计算基数',
  `period_length` int(11) DEFAULT NULL COMMENT '周期长度',
  `period_unit` varchar(32) DEFAULT NULL COMMENT '周期单位',
  `repay_method` varchar(32) DEFAULT NULL COMMENT '还款方式',
  `whole_sale` bit(1) DEFAULT NULL COMMENT '是否趸缴',
  `loan_time` date DEFAULT NULL COMMENT '需放款日期',
  `actual_loan_day` date DEFAULT NULL COMMENT '实际放款日期',
  `grant_credit_time` datetime DEFAULT NULL COMMENT '授信日期',
  `overdue_repay_base_liquidated` varchar(32) NOT NULL DEFAULT 'MONTHLY_REPAY' COMMENT '违约金计算基数',
  `sale_type` varchar(32) DEFAULT NULL COMMENT '贷款模式',
  `guarantee_fee_type` varchar(32) NOT NULL DEFAULT 'NO_GUARANTEE_FEE',
  `fund_mode` varchar(32) NOT NULL DEFAULT 'ORIDINARY',
  `mgmt_fee_mode` varchar(64) NOT NULL DEFAULT 'DEFAULT' COMMENT '服务费计算模式',
  `compliance_charged_rule` varchar(32) NOT NULL DEFAULT 'DEFAULT' COMMENT '计费规则',
  PRIMARY KEY (`id`),
  KEY `idx_debt_exts_fund_source` (`fund_source`),
  KEY `idx_debt_exts_channel_type` (`channel_type`),
  KEY `idx_debtExt_repay_method` (`repay_method`) USING BTREE,
  KEY `idx_debtExt_overdue_repay_base` (`overdue_repay_base_penalty`) USING BTREE,
  KEY `idx_debtExt_inadvanceRepayLiquidatedFeeBase` (`inadvance_repay_liquidated_fee_base`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2033155 DEFAULT CHARSET=utf8

CREATE TABLE `debts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `relation_id` int(11) NOT NULL COMMENT '关联数据id(进件id)',
  `source` varchar(16) NOT NULL DEFAULT 'THREAD' COMMENT '数据来源',
  `state` varchar(32) NOT NULL COMMENT '还款状态',
  `last_repay_date` date DEFAULT NULL COMMENT '最近一次还款日',
  `actual_end_date` date DEFAULT NULL COMMENT '实际结清日期',
  `current_phase` int(11) NOT NULL DEFAULT '0' COMMENT '当前期',
  `total_phases` int(11) NOT NULL COMMENT '总期数',
  `rest_phases` int(11) NOT NULL DEFAULT '0' COMMENT '剩余期数',
  `repaid_phases` int(11) NOT NULL DEFAULT '0' COMMENT '正常结清期数',
  `advance_phase` int(11) NOT NULL DEFAULT '0' COMMENT '提前结清期号',
  `overdue_repaid_phases` int(11) NOT NULL DEFAULT '0' COMMENT '逾期已还期数',
  `reserve_phases` int(11) NOT NULL DEFAULT '0' COMMENT '已垫付期数',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  `entrust_date` date DEFAULT NULL COMMENT '代偿日',
  `calculate_date` datetime DEFAULT NULL,
  `debt_ext_id` int(11) NOT NULL COMMENT '关联债务附加表id',
  `calculate_param_id` int(11) DEFAULT NULL COMMENT '计算参数ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `debts_relation_id_IDX` (`relation_id`,`source`) USING BTREE,
  UNIQUE KEY `debts_debt_ext_id_IDX` (`debt_ext_id`) USING BTREE,
  KEY `idx_debts_phase` (`current_phase`),
  KEY `idx_debts_state` (`state`),
  KEY `idx_debts_last_repay_date` (`last_repay_date`),
  KEY `idx_debts_calculateParamId` (`calculate_param_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2033178 DEFAULT CHARSET=utf8

CREATE TABLE `debt_cycle` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `relation_id` int(11) NOT NULL COMMENT '进件Id',
  `debt_id` int(11) NOT NULL COMMENT '债务Id',
  `business_type` varchar(32) NOT NULL COMMENT '业务类型',
  `user_name` varchar(64) NOT NULL COMMENT '用户名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_relation_id` (`relation_id`),
  KEY `idx_debt_id` (`debt_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16684314 DEFAULT CHARSET=utf8
